"""empty message

Revision ID: f448887581b6
Revises: 
Create Date: 2024-02-04 10:05:12.023449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f448887581b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortcodes',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('shortcode', sa.Text(), nullable=False),
    sa.Column('redirect_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcode')
    )
    op.create_index(op.f('ix_short_codes_id'), 'shortcodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_codes_id'), table_name='shortcodes')
    op.drop_table('shortcodes')
    # ### end Alembic commands ###
