version: "3.8"

name: tiny

services:
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
      target: run-development
    hostname: tiny
    restart: always
    env_file: ../../.env
    ports:
      - "8095:8095"
    depends_on:
      - pg
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+asyncpg://tiny:tiny@pg/tiny"
      FASTAPI_APP_FACTORY: "tiny.__main__:create_app"
    volumes:
      - ../..:/tiny/src

  pg:
    image: postgres:13
    hostname: pg-cts
    ports:
      - "127.0.0.1:11532:5432"
    environment:
      POSTGRES_DB: tiny
      POSTGRES_USER: tiny
      POSTGRES_PASSWORD: tiny
    volumes:
      - ./.local/pg-data:/var/lib/postgresql/data
